---
- name: Converge
  hosts: all
  # pre_tasks:
  #   - name: update apt cache.
  #     apt: update_cache=yes cache_valid_time=3600
  vars:
    ansible_user: ansible
  roles:
    - role: geerlingguy.git
    - role: jerryshockley.dotfiles

  tasks:
