---
extends: default

ignore: '/Users/jerrys/.ansible/roles/geerlingguy.git'

rules:
  line-length:
    max: 120
    level: warning
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
